services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\SysNote\:
    resource: '../Classes/*'

  dashboard.widget.sys_notes.all:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_all'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.all.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.all.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'


  dashboard.widget.sys_notes.default:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
        category: 0
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_default'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteDefault.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteDefault.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.sys_note_instructions:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
        category: 1
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_instructions'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteInstructions.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteInstructions.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.sys_note_template:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
        category: 2
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_template'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteTemplate.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteTemplate.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.sys_note_notes:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
        category: 3
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_notes'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteNotes.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteNotes.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'

  dashboard.widget.sys_notes.sys_note_todos:
    class: 'TYPO3\CMS\SysNote\Widgets\PagesWithInternalNote'
    arguments:
      $options:
        refreshAvailable: true
        category: 4
    tags:
      - name: dashboard.widget
        identifier: 'sys_note_todos'
        groupNames: 'sys_note'
        title: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteToDos.title'
        description: 'LLL:EXT:sys_note/Resources/Private/Language/locallang.xlf:widget.pagesWithInternalNoteToDos.description'
        iconIdentifier: 'content-note'
        height: 'medium'
        width: 'medium'
